Efe Sayik <efesyk3422@gmail.com>
16:15 (0 dakika önce)
Alıcı: ben

name: Build Jar

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v3
- name: Set up JDK 21
uses: actions/setup-java@v3
with:
distribution: 'temurin'
java-version: '21'
- name: Build with Maven
run: mvn -B package
- name: Upload artifact
uses: actions/upload-artifact@v3
with:
name: YukseklikGoster
path: target/*.jar
